config/routes.rb
Rails.application.routes.draw do

    resource :sessions, only: [:create, :new, :destroy]

  resources :users, except: [:destroy]

  resources :recipes

  root 'recipes#index'

end

app/models/ingredient.rb
class Ingredient
  include Mongoid::Document
  field :name, type: String
end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  field :name, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_secure_password
  field :email, type: String
  field :password_digest, type: String

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authorize
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	@current_user ||= User.where(id:session[:user_id]).first
  end

  def logged_in?
		current_user != nil
	end

  def authorize
    redirect_to new_sessions_path, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	def index
		@ingredients = Ingredient.all
	end
	
end

app/controllers/recipes_controller.rb
require 'httparty'
require 'json'

class RecipesController < ApplicationController

	def index 
		if params[:query] 
    	query = URI.escape(params[:query])

		my_api_key = ENV["YM_API_KEY"]
		my_api_secret = ENV["YM_API_SECRET"]

		# raise params[:recipe].to_s
		recipe_search_uri = "http://api.yummly.com/v1/api/recipes?_app_id="+my_api_key+"&_app_key="+my_api_secret+"&q="+ query + "&requirePictures=true"
		response = HTTParty.get(recipe_search_uri).to_json	
		recipe_search = JSON.parse(response)
		recipeid = []
		# we're going to loop through my search results for recipes. each RS is one search result
		recipe_search['matches'].each do |rs|
			recipeid.push(rs['id'])
		end
    # go through each recipeid and make and api call for each item in that recipe id to search for picture and link.
    @recipe_get = []
    recipeid.each do |r|
		  recipe_get_uri = "http://api.yummly.com/v1/api/recipe/"+ r +"?_app_id="+my_api_key+"&_app_key="+my_api_secret
      get_response = HTTParty.get(recipe_get_uri).to_json  
      @recipe_get.push(JSON.parse(get_response))
    end
		end
		
    end


		#@next = @matches["imageUrlsBySize"]


		#raise @match.inspect


	end

	def show
		
	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  
  def new
  	@user = User.new
  	@is_login = true
  end
  
  def create
    u = User.where(email:params[:user][:email]).first
    if u && u.authenticate(params[:user][:password])
      session[:user_id] = u.id.to_s
      redirect_to root_path
    else
      redirect_to new_sessions_path
    end
  end

  def destroy
    reset_session
    redirect_to new_sessions_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully logged out.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grubify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<!-- adds jquery for twitter bootstrap -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body class="bodyBG">

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav navbar-nav">
      
          <% if current_user %>
          <li class="icon-bar"><%=link_to "Grubify",root_path %></li>
          <li class="icon-bar"><%=link_to "Log Out", sessions_path, method: :delete %></li>

          <% else %>

          <li class="icon-bar"><%=link_to "Sign Up", new_user_path %></li>
          <li class="icon-bar"><%=link_to "Log In", new_sessions_path %></li>

          <% end %> 

        
      </ul>
    </div>
  </div>
</nav>

<%= yield %>


</body>
</html>

app/views/recipes/index.html.erb
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4"><h1>Recipe Search</h1></div>
    <div class="col-md-4"></div>
  </div>
  <div class="row">
    <div class="col-md-4"></div>

    <div class="col-md-4">


      <%= form_tag recipes_path, :method => 'get' do %>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag "Grubify", :name => nil %>
      <% end %>
      <br>

      <% if @recipe_get %>	
      <% @recipe_get.each do |r| %>
        
        <ul>
          <li class="recipes"><strong> <%= r['attribution']['text'] %> <strong>
   	      <%= link_to image_tag(r['images'][0]['hostedLargeUrl']), r['source']['sourceRecipeUrl'], :class => "image_style" %> </li><br><br>
        </ul>
  </div>
  <div class="col-md-4"></div>
  </div>
  
	 

<% end %>
<% end %> 

app/views/recipes/show.html.erb
<!-- <p>
  <strong>Home:</strong>
  <%= @recipe.home %>
</p> -->

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :email, :placeholder => "email" %>
  </div> </br>
  <div class="field">
    <%= f.password_field :password, :placeholder => "password" %>
  </div> </br>
  <div class="field">
    <%= f.password_field :password_confirmation, :placeholder => "confirm password" %> 
  </div> </br>
  <div class="actions">
    <%= f.submit %> 
  </div>
<% end %>

app/views/users/index.html.erb
<!-- <h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_confirmation %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">

          <h1>Sign up</h1>

          <%= render 'form' %>

          <%= link_to 'Back', users_path %>

        </div>
      </div>

    </div>
    <div class="col-md-4"></div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>